config/routes.rb
Rails.application.routes.draw do
  resources :interns
  devise_for :users 
  resources :pages

  #get 'pages/index'
    
  root "pages#index"

  #get 'pages/afterLogin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/intern.rb
class Intern < ApplicationRecord
	belongs_to :user
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

	has_many :interns
	
	validates :email, presence: true,
	                      length: { minimum: 10 }
	validates :password, presence: true,
	                     length: { minimum: 6 }

	devise :database_authenticatable, :registerable,
	         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/interns_controller.rb
class InternsController < ApplicationController
  before_action :set_intern, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  

  # GET /interns
  # GET /interns.json
  def index
    @interns = Intern.all
  end

  # GET /interns/1
  # GET /interns/1.json
  def show
  end

  # GET /interns/new
  def new
    @intern = Intern.new
  end

  # GET /interns/1/edit
  def edit
  end

  # POST /interns
  # POST /interns.json
  def create
    @intern = Intern.new(intern_params)

    respond_to do |format|
      if @intern.save
        format.html { redirect_to @intern, notice: 'Intern was successfully created.' }
        format.json { render :show, status: :created, location: @intern }
      else
        format.html { render :new }
        format.json { render json: @intern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interns/1
  # PATCH/PUT /interns/1.json
  def update
    respond_to do |format|
      if @intern.update(intern_params)
        format.html { redirect_to @intern, notice: 'Intern was successfully updated.' }
        format.json { render :show, status: :ok, location: @intern }
      else
        format.html { render :edit }
        format.json { render json: @intern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interns/1
  # DELETE /interns/1.json
  def destroy
    @intern.destroy
    respond_to do |format|
      format.html { redirect_to interns_url, notice: 'Intern was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intern
      @intern = Intern.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def intern_params
      params.require(:intern).permit(:fullName, :otherName, :institution, :registrationNumber, :program, :year, :gender, :emailAdress, :profilePic)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def afterLogin
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interns_helper.rb
module InternsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/interns/_form.html.erb
<%= form_for(intern, :html => { multipart: true }) do |f| %>
  <% if intern.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intern.errors.count, "error") %> prohibited this intern from being saved:</h2>

      <ul>
      <% intern.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="top-content">
    <div class="inner-bg">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-8">
              <div class="form-box">
                <div class="form-top">
                  <div class="form-top-left">
                    <h1>Account Registration.<span class="blinking-cursor">_</span></h1>
                      <p>Fill in the form below to get instant access:</p>
                  </div>
                </div>

                    <div class="form-bottom">
                      <form role="form" action="" method="post" class="registration-form">
                        <div class="form-group">

                            <%= f.text_field :fullName, placeholder:"Full Name ..." %>
                        </div>
                        <div class="field">

                            <%= f.text_field :otherName, placeholder:"Other Names ..." %>
                        </div>
                        <div class="field">

                            <%= f.text_field :institution, placeholder: "Institution (University) ..." %>
                        </div>
                        <div class="field">

                            <%= f.text_field :registrationNumber, placeholder: "Registration Number ..." %>
                        </div>
                        <div class="field">

                            <%= f.text_field :program, placeholder: "Program ..." %>
                        </div>
                        <div class="field">

                            <%= f.text_field :year, placeholder: "Year Of Study (I,II,IV,) ..." %>
                        </div>
                        <div class="field">

                            <%= f.text_field :gender, placeholder: "Gender ..." %>
                           
                        </div>
                        <div class="field">

                            <%= f.text_field :emailAdress, placeholder: "Email Address (example@something.com)" %>
                        </div>
                        <div class="field">

                            <%= f.file_field :profilePic, class: "form-control" %>
                        </div>
                        <div class="actions">
                           <button type="submit" class="btn">Sign me up!</button>
                        </div>
                        </form>
                    </div>
                 </div>


             </div>

             


         </div>
      </div>
  </div>
  <% end %>

app/views/interns/edit.html.erb
<h1>Editing Intern</h1>

<%= render 'form', intern: @intern %>

<%= link_to 'Show', @intern %> |
<%= link_to 'Back', interns_path %>

app/views/interns/index.html.erb
<p id="notice"><%= notice %></p>
    <div class="container-fluid">
      <div class="panel panel-success" style="border:2px solid #d6e9c6;">
        <div class="panel-heading">

            <h1 style="text-align:center;">Interns at Joadah & iDealinks Ltd</h1><%= link_to 'New Intern', new_intern_path, class: "btn btn-primary" %>
            <hr style="width:100%; color: #ddd; background-color: #ddd;">

             
              <p id="notice"><%= notice %></p>
          </div>
        <div class="panel-body">
          <div class="table-responsive">

        <div id="no-more-tables">
            <table class="col-md-12 table-bordered table-striped table-condensed cf">
            <thead class="cf">
              <tr>
                <tr>
                  <th>Fullname</th>
                  <th>Othername</th>
                  <th>Profilepic</th>
                  <th>Institution</th>
                  <th>Registrationnumber</th>
                  <th>Program</th>
                  <th>Year</th>
                  <th>Gender</th>
                  <th>Emailadress</th>
                 
                  <th colspan="3"> </th>
                </tr>
              </tr>
            </thead>

            <tbody>
              <% @interns.each do |intern| %>
                <tr>
                  <td><%= intern.fullName %></td>
                  <td><%= intern.otherName %></td>
                  <td><%= intern.profilePic %></td>
                  <td><%= intern.institution %></td>
                  <td><%= intern.registrationNumber %></td>
                  <td><%= intern.program %></td>
                  <td><%= intern.year %></td>
                  <td><%= intern.gender %></td>
                  <td><%= intern.emailAdress %></td>
                  
                  <td><%= link_to 'Show', intern %></td>
                  <td><%= link_to 'Edit', edit_intern_path(intern) %></td>
                  <td><%= link_to 'Destroy', intern, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>

            
          </table>
        </div>
    </div>
  </div>
  </div>
</div>
   

app/views/interns/new.html.erb
<%= render 'form', intern: @intern %>

<%= link_to 'Back', interns_path %>

app/views/interns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @intern.fullName %>
</p>

<p>
  <strong>Othername:</strong>
  <%= @intern.otherName %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @intern.institution %>
</p>

<p>
  <strong>Registrationnumber:</strong>
  <%= @intern.registrationNumber %>
</p>

<p>
  <strong>Program:</strong>
  <%= @intern.program %>
</p>

<p>
  <strong>Year:</strong>
  <%= @intern.year %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @intern.gender %>
</p>

<p>
  <strong>Emailadress:</strong>
  <%= @intern.emailAdress %>
</p>

<p>
  <strong>Profilepic:</strong>
  <%= image_tag (@intern.image_url.to_s) %>
 

</p>

<%= link_to 'Edit', edit_intern_path(@intern) %> |
<%= link_to 'Back', interns_path %>

app/views/layouts/_afterLogin.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><%= image_tag("logo.png")%></a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#home">Internship</a></li>
          <li><a href="#home">Profile</a></li>
          <li><a href="#band">Settings</a></li>
          <li><a href="#tour" data-toggle="modal" data-target="#edit" >Sign Out</a></li>
        </ul>
      </div>
    </div>
</nav>

        <div class="container-fluid">

          <div class="move">
           <div class="panel panel-success" style="border:2px solid #d6e9c6;">
          <div class="panel-heading">
              <h1 style="text-align:center;">User Profile</h1>
          </div>

          <div class="panel-body" style="background-color: #f0f0f0;">
          
            <div class="row">
              <div class="col-md-4">
              <div class="card card-user">
                <div class="image">
                      <%= image_tag("1.jpg") %>
                </div>

                <div class="content">
                    <div class="author">
                        <%= image_tag("cico.jpg", class: "avatar border-white") %>
                      <h3 class="title">Matenga Ivan Ogarubo<br />
                      <h4>Position: Intern<h4>
                      <h4>Department: IT <h4>
                      <p><a href="#">Muni University</a></p>
                      </h3>
                    </div>
                    <p class="description text-center">
                      
                      </p>

                      <hr class="pd-10">
                  <div class="row">
                  <div class="col-sm-12 profile-actions text-left">
                  
                    <button type="button" class="btn1 btn-primary btn-sm"><i class="fa fa-envelope"></i> Send Message</button>
                    
                     <button type="button" class="btn1 btn-primary btn-sm"><i class="fa fa-envelope"></i>Download</button>

                     <button type="button" class="btn1 btn-primary btn-sm"><i class="fa fa-envelope"></i>Upload</button>

                    <button type="button" class="btn1 btn-success btn-sm"><i class="fa fa-check"></i>Messages</button>

                    <span style="color:gray; font-size:12px;"><i>3 Weeks left</i></span>
                  </div>
                </div>
              </div>
                    
              </div>
            </div>
      
            <div class="col-md-8">
              <div class="card"> 
                <div class="header"><h4>Timeline (Profile)<hr class="pd-10"></h4>
                    <h3>About</h3>
                    <div class="row">
                      <div class="col-md-2">Name</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">Matenga Ivan Ogarubo</span>
                      </div>

                      <div class="col-md-2">Email</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">mivan774@gmail.com</span>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-2">Institution</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">Muni University</span>
                      </div>

                      <div class="col-md-2">Phone Number</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">(+256) 773 996 470</span>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-2">Course</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">BSc Information Systems</span>
                      </div>

                      <div class="col-md-2">Satus</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">Intern</span>
                      </div>

                    </div>


                    <div class="row">
                      <div class="col-md-2">Year</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;"> III </span>
                      </div>

                      <div class="col-md-2">Interest (Area of Expertise)</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;"> UI/UX Development </span>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-2">Skills</div>
                      <div class="col-md-4">
                        <span style="color:gray; font-size:16px;">Autocad, Rails, Ionic, Python, php, AI </span>
                      </div>
                    </div>

                    <hr class="pd-10">
                    <h4>Profile Edit</h4>
                     <div class="row">

                    <div class="col-md-4">
                      <div class="form-group">
                        <input class="form-control border-input" placeholder="Name" type="text">
                      </div>
                    </div>
                  </div>

                  <div class="row">

                    <div class="col-md-4">
                      <div class="form-group">
                        <input class="form-control border-input" placeholder="Course" type="text">
                      </div>
                    </div>
                  </div>

                  <div class="row">

                    <div class="col-md-4">
                      <div class="form-group">
                        <input class="form-control border-input" placeholder="Instituion" type="text">
                      </div>
                    </div>
                  </div>

                  <div class="row">

                    <div class="col-md-4">
                      <div class="form-group">
                        <input class="form-control border-input" placeholder="Skills" type="text">
                      </div>
                    </div>
                  </div>

                  <div class="row">

                    <div class="col-md-4">
                      <div class="form-group">
                        <input class="form-control border-input" placeholder="Area of Expertise" type="text">
                      </div>
                    </div>
                  </div>

                </div>
                  </div>
                </div>
              </div>
              
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>

app/views/layouts/_modal.html.erb
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 class="modal-title custom_align" id="Heading" style="color:#1fa67b; text-align:center;">Please Login in to continue..</h3>
                
            </div>
            <div class="modal-body">
                <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                
                <div class="field">
                    <%= f.email_field :email, autofocus: true, class:"form-control ", placeholder:"Email Address" %>
                </div> <br/>
                
                <div class="field">
                    <%= f.password_field :password, autocomplete: "off",class:"form-control", placeholder:"Password" %>
                </div>
                
                  <% if devise_mapping.rememberable? -%>
                <div class="field">
                  <%= f.check_box :remember_me %>
                  <%= f.label :remember_me, class: "remember_me"%>
                  
                </div>
                <% end -%>
                <% end %>
            </div>
            
            <div class="modal-footer ">
                <div class="actions">
                <%= f.submit "Log in", class:"btn btn-info btn-lg btn-block", width: "100%" %>
              </div>
                <span style="display: inline;"><%= render "devise/shared/links" %></span>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
</div>
<!--SIgn up modal-->

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><%= image_tag("logo.png")%></a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><a href="#home">Noticeboard</a></li>
          <li><%= link_to "Apply", new_intern_url %></li>
          <li><a href="#band">Internees</a></li>
          <li><a href="#tour">Training</a></li>
          <li><a href="#tour" data-toggle="modal" data-target="#edit" >Login</a></li>
          <li><a href="#tour" data-toggle="modal" data-target="#register">Sign Up</a></li>

          <li><a href="#"><span class="glyphicon glyphicon-search"></span></a></li>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/_signUp.html.erb
<div class="modal fade" id="register" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 class="modal-title custom_align" id="Heading" style="color:#1fa67b; text-align:center;">Please Sign Up to apply</h3>
            
        </div>
        <div class="modal-body">
            <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%= devise_error_messages! %>
     
            <div class="field">
                <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Email Address", type: "email" %>
            </div>
            
            <div class="field">
                <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
                <% end %><br/>
                <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Password (6 Characters Minimum)" %>
            </div>
            <br/>
            
            <div class="field">
                <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: "Password Confirmation" %>
            </div>
        </div>

        <div class="modal-footer ">
             <div class="actions">
                <%= f.submit "Sign up Now", class: "btn btn-success btn-lg btn-block" %>
              </div>
        </div>
            
        <% end %>

        <%= render "devise/shared/links" %>
       
    </div>
    <!-- /.modal-content -->
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InternApp2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
   
  </body>
</html>

app/views/pages/index.html.erb
<%= render 'layouts/nav'%>
<div class="slider">		
<div id="about-slider">
    <div id="carousel-slider" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators visible-xs">
            <li data-target="#carousel-slider" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-slider" data-slide-to="1"></li>
            <li data-target="#carousel-slider" data-slide-to="2"></li>
        </ol>

        <div class="carousel-inner">
            <div class="item active">						
                <%= image_tag("1.jpg")%>
                <div class="carousel-caption">
                    <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.3s">								
                        <h3>JOADAH CONSULTS LTD</h3>
                        <h4>"Engineers with integrity"</h4>

                    </div>
                    <div class="col-md-10 col-md-offset-1">
                        <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.6s">								
                            <h2>INTERNSHIP MANAGEMENT PLATFORM</h2>
                        </div>
                    </div>
                    <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.9s">								
                        <form class="form-inline">
                             
                           <%= link_to "Apply Now", new_intern_path,class: "btn btn-default btn-lg",'data-target' => '#edit', id: "btn-default" %>

                        </form>
                    </div>
                </div>
            </div>

            <div class="item">
               <%= image_tag("2.jpg") %>
                <div class="carousel-caption">
                    <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.3s">								
                        <h3>JOADAH CONSULTS LTD</h3>
                        <h4>"Engineers with integrity"</h4>

                    </div>
                    <div class="col-md-10 col-md-offset-1">
                        <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.6s">								
                            <h2>INTERNSHIP MANAGEMENT PLATFORM</h2>
                        </div>
                    </div>
                    <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.9s">								
                        <form class="form-inline">
                            <a href="#about" class="btn btn-default btn-lg" id="btn-default">Apply Now</a>
                        </form>
                    </div>
                </div>
            </div> 
            <div class="item">
                <%= image_tag("3.jpg") %>
                <div class="carousel-caption">
                    <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.3s">								
                        <h3>JOADAH CONSULTS LTD</h3>
                        <h4>"Engineers with integrity"</h4>

                    </div>
                    <div class="col-md-10 col-md-offset-1">
                        <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.6s">								
                            <h2>INTERNSHIP MANAGEMENT PLATFORM</h2>
                        </div>
                    </div>
                    <div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.9s">								
                        <form class="form-inline">
                            <a href="#about" class="btn btn-default btn-lg" id="btn-default">Apply Now</a>
                        </form>
                    </div>
                </div>
            </div> 
        </div>

        <a class="left carousel-control hidden-xs" href="#carousel-slider" data-slide="prev">
            <i class="fa fa-angle-left"></i> 
        </a>

        <a class=" right carousel-control hidden-xs"href="#carousel-slider" data-slide="next">
            <i class="fa fa-angle-right"></i> 
        </a>
    </div> <!--/#carousel-slider-->
</div><!--/#about-slider-->
</div><!--/#slider-->




<footer>
<div class="container">
    <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
        <span style="color:#666363; font-size:30px; display:flex;"><img src="img/footer-logo.png" class="img-responsive" alt="">&nbsp| Location</span>
        <hr>

        <p>We are located the Joadah Construction co</p>						
        <div class="contact-info">
            <ul>
                <li><i class="fa fa-home fa"></i> Plot 7 Bugolobi | Redstone House Floor 5 </li>
                <li><i class="fa fa-phone fa"></i> +25663636356336</li>
                <li><i class="fa fa-envelope fa"></i> info@joadahconsult.com</li>
                <li><i class="fa fa-globe fa"></i> www.joadahconsult.com</li>
            </ul>
        </div>
    </div>

    <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">				
        <div class="text-center">
            <span style="color:#666363; font-size:30px; display:flex; padding-bottom: 8px;">About Joadah Consult</span>
        <hr>

        <p style=" marging-right:10px">Joadah Consult is a limited liability company with a proven set-up for Infrastructure and Management Consultancy projects with all the technical and financial capabilities of undertakingany size of project</p>

        <p>Joadah Consult provides superior consulting services in design and project management</p>
        </div>
    </div>

    <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="900ms">				
        <div class="">
            <div class="text-center">
            <span style="color:#666363; font-size:30px; display:flex; padding-bottom: 8px;">Subscribe for News</span>
        <hr>
        </div>
            <div class="btn-gamp">		
                <input type="email" class="form-control" id="exampleInputEmail3" placeholder="Enter Email">
            </div>
            <div class="btn-gamp">
                <a type="submit" class="btn btn-default">Subscribe</a>
            </div>

    </div>  
</div>

</div>	
</footer>

<div class="sub-footer">
<div class="container">
    <div class="social-icon">
        <div class="col-md-4">
            <ul class="social-network">
                <li><a href="#" class="fb tool-tip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#" class="twitter tool-tip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#" class="gplus tool-tip" title="Google Plus"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#" class="linkedin tool-tip" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#" class="ytube tool-tip" title="You Tube"><i class="fa fa-youtube-play"></i></a></li>
            </ul>	
        </div>
    </div>

    <div class="col-md-4 col-md-offset-4">
        <div class="copyright">
            &copy; Joadah Co. All Rights Reserved.
        </div>
    </div>						
</div>				
</div>


<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<h3 class="modal-title custom_align" id="Heading" style="color:#1fa67b;">Please Login in to continue..</h3>
<h5 class="modal-title custom_align" id="Heading" style="color:#888;">Enter your Email Address and Password to Sign in</h5>
</div>
<div class="modal-body">
<div class="form-group">
<input class="form-control " type="text" placeholder="Email Address">
</div>

<div class="form-group">
<input class="form-control " type="password" placeholder="Password">
</div>

<div class="form-group">
<span style="color:gray; padding:10px;"><input class="check_box" type="checkbox" value="1" name=" " > Remember Me</span>
</div> 
</div>

<div class="modal-footer ">
<button type="button" class="btn btn-warning btn-lg" style="width: 100%;"><span class="glyphicon glyphicon-ok-sign"></span> Login</button>
</div>
</div>
<!-- /.modal-content -->
</div>
</div>


<div class="modal fade" id="register" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<h3 class="modal-title custom_align" id="Heading" style="color:#1fa67b;">Please fill the form below to Sign Up..</h3>
<h5 class="modal-title custom_align" id="Heading" style="color:#888;">Use your Email Address and Password to Sign Up</h5>
</div>
<div class="modal-body">
<div class="form-group">
<input class="form-control " type="text" placeholder="Email Address">
</div>

<div class="form-group">
<input class="form-control " type="password" placeholder="Password (6 Characters Mininum)">
</div>

<div class="form-group">
<input class="form-control " type="password" placeholder="Re-type Password (Comfirmation)">
</div>


</div>

<div class="modal-footer ">
<button type="button" class="btn btn-warning btn-lg" style="width: 100%;"><span class="glyphicon glyphicon-ok-sign"></span>Sign Up Now!</button>
</div>
</div>
<!-- /.modal-content -->
</div>
</div>



<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.js"></script>		
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>	
<script src="js/wow.min.js"></script>
<script>wow = new WOW({}).init();</script>	